---
-
  become: true
  hosts: CLNT2_CLNT3
  name: "Test connection to my Test servers"
  vars:
    ansible_sudo_pass: 


  tasks:
    -
      name: "Ping my servers"
      ping: ~
    -
      debug:
        var: ansible_distribution
      name: "Name remote server OS"
    -
     ansible.builtin.reboot:

    -
      delegate_to: "127.0.0.1"
      name: "wait  till my server will come online"
      wait_for:
        delay: 30
        host: "{{ ansible_hostname }}"
        state: started
        timeout: 60
